[project]
name = 'marxet'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.happy-welsh]
path = 'contracts/happy-welsh.clar'
clarity_version = 2
epoch = 2.4

[contracts.marxet]
path = 'contracts/marxet.clar'
clarity_version = 2
epoch = 2.4

[contracts.materials]
path = 'contracts/materials.clar'
clarity_version = 2
epoch = 2.4

[contracts.sip010-token]
path = 'contracts/sip010-token.clar'
clarity_version = 2
epoch = 2.4

[contracts.stacks-satoshis]
path = 'contracts/stacks-satoshis.clar'
clarity_version = 2
epoch = 2.4
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = true
callee_filter = true
